version: 2
jobs:
  deploy:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: npm i
      - run: npm run build
      - run: ./scripts/gh-deploy.sh dist

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
